### ISSUE TITLE
Test resulting patched EBOOT in PS3HEN

### ISSUE THREAD

**Issue by AShifter** [LBPUnion/UnionPatcher#17]
UnionRemotePatcher seems to be capable of patching (and most importantly, signing) game EBOOTs for use on CFW such as EVILNAT 4,88.2, but it's essential to ensure compatibility across the board if we're going to get as many people as possible to connect.

The most basic requirements for running UnionRemotePatcher should be, in theory, a PS3 console with HEN and WebMan/MOD installed, and for a network copy, PS3MAPI enabled in WebMan's settings. We would appreciate it if you could test UnionRemotePatcher on HFW and let us know how it goes down in the comments on this issue.

**Comment by jvyden** [comment]
Its been a few months and it seems to be working across all custom firmwares; I haven't heard a peep about compatibility.
