### ISSUE TITLE
i get error while patching for ps3

### ISSUE THREAD

**Issue by sidthecat454** [LBPUnion/UnionPatcher#39]
![Screenshot 2023-12-17 160907](https://github.com/LBPUnion/UnionPatcher/assets/144497618/f7c50a2a-e5b5-4b11-a934-e45011456080)

**Comment by Zaprit** [comment]
You need to enable PS3MAPI in the WebMAN-MOD settings please see the [patching tutorial](https://www.lbpunion.com/post/how-to-patch-littlebigplanet-ps3-for-project-lighthouse/) for more information.
