### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by Overzaxy** [LBPUnion/UnionPatcher#40]
![IMG_2023](https://github.com/LBPUnion/UnionPatcher/assets/155002093/2b121694-1508-4e21-8226-a81ac08dc3b1)

**Comment by Zaprit** [comment]
So a few things, what have you got as your ps3 ip address, is your ps3 on, cfw/hen jailbroken, is webman-mod or similar FTP server installed etc.

**Comment by Zaprit** [comment]
Feel free to re-open if you're still having issues, though a better place to ask for support is the LBP Union Discord.
