### ISSUE TITLE
Lack of usage instructions or warnings

### ISSUE THREAD

**Issue by 505e06b2** [LBPUnion/UnionPatcher#7]
Use of this tool requires knowledge of decrypting SELF files, which are then scanned for text to be replaced. It is then up to the user to encrypt them again and place them onto their system. This doesn't seem to be very well conveyed. The instructions will differ for both of the PS3/PSV platforms and not likely be an entirely automatic process, so will both need written instructions

In the program, it may also be useful to:
* Check the header for an ELF signature (file begins with the magic number of 0x7F, followed by ELF(45 4c 46))
    * It is probably worthwhile to assert the instruction set being ARM/PowerPC, appropriate endianess, and word size
* Ensure at least 4(?) matching URLs have been found - non matching URLs should throw at least a warning

As soon as my PR: #6  is merged, I will be more than happy to help with this

Cheers

**Comment by jvyden** [comment]
Running a couple checks on the ELF sounds fine, but as for instructions we have been working on some guides in our Union Space Corps beta testing program which we will publish closer to Project Lighthouse's release.

I doubt those instructions will be all that useful anyways, since @AShifter is working on a version of the patcher that does more of the manual part.

**Comment by 505e06b2** [comment]
Would this new version include decrypting/re-encrypting the SELF? From what I've seen, for Vita, you have to decrypt it on the console itself, at least for the moment

**Comment by jvyden** [comment]
Yes, however Vita is not a priority at the moment.

**Comment by 505e06b2** [comment]
Just as an update, I've started work on abstracting out the ELF part to allow for better file detection. I have access to both a PS3 and Vita executable so this _should_ be thoroughly manually tested
Are there requirements for automated testing in this repo?
